version: '3.8'

services:
  neo4j:
    image: neo4j:5.26-community-ubi9
    container_name: llm_neo4j
    restart: unless-stopped
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
      - NEO4J_DEPRECATION_WARNING=suppress
      - NEO4J_server_http_advertised__address=neo4j.anyone.ganeshait.com:443
      - NEO4J_server_bolt_advertised__address=neo4j.anyone.ganeshait.com:7687

      # Tell Neo4j to handle its own SSL securely
      - NEO4J_server_bolt_tls__level=REQUIRED
      - NEO4J_dbms_ssl_policy_bolt_enabled=true
      - NEO4J_dbms_ssl_policy_bolt_base__directory=/certs
      - NEO4J_dbms_ssl_policy_bolt_private__key=privkey.pem
      - NEO4J_dbms_ssl_policy_bolt_public__certificate=fullchain.pem
    ports:
      - "7474:7474" 
      # - "127.0.0.1:7688:7687" # Bolt port (Untuk koneksi dari aplikasi LLM nanti)
      - "7687:7687" # Exposed directly to the public now
    volumes:
      - neo4j_data:/data
      - ./certs:/certs:ro # Mount the certificates we just copied
    networks:
      - anyone_network
  
  redis:
    image: redis:8.6-trixie
    container_name: llm_redis
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_PASSWORD} # Simpan data ke disk setiap 60 detik jika ada 1 perubahan
    volumes:
      - redis_data:/data
    networks:
      - anyone_network

volumes:
  neo4j_data:
  redis_data:

networks:
  anyone_network:
    external: true